### ISSUE TITLE
Is XLA_PYTHON_CLIENT_PREALLOCATE needed for this?

### ISSUE THREAD

**Issue by euclaise** [lucidrains/jax2torch#2]
Hello,

My understanding was that Jax preallocates ~90% of the GPU memory, and setting XLA_PYTHON_CLIENT_PREALLOCATE to false is needed when interoping with other frameworks in order to avoid this.  However, this isn't mentioned anywhere here. I figure this should probably be explicitly mentioned?

The SMURF repo does set `os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"`, so I assume it is necessary?

**Comment by lucidrains** [comment]
yeah sure! welcome a PR with that being shared in the readme

**Comment by lucidrains** [comment]
I don't think that can be taken care of within the repo, as env should be set as early as possible

**Comment by euclaise** [comment]
https://github.com/lucidrains/jax2torch/pull/3
